name: Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '18'
      - run: |
          npm ci
          npm run all
          git config user.name Noah Reinalter
          git config user.email 38698485+noahreinalter@users.noreply.github.com
          git add .
          today=$(date +'%-d.%-m.%Y')
          git diff-index --quiet HEAD || (git commit -m "Updated build file ${today}" && git push)
